import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#afecff",
        "surface-bright": "#faf9ff",
        "on-primary-fixed": "#001848",
        "on-tertiary-fixed": "#001f27",
        "on-background": "#051a3e",
        "on-tertiary-container": "#76e2ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#4633a0",
        "on-primary-container": "#c4d2ff",
        "secondary-fixed": "#e5deff",
        "outline": "#737685",
        "tertiary-fixed-dim": "#48d7f9",
        "tertiary-container": "#006477",
        "inverse-surface": "#1d3054",
        "primary-fixed-dim": "#b2c5ff",
        "secondary-container": "#9f8eff",
        "surface-dim": "#ccdaff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004e5d",
        "on-primary-fixed-variant": "#0040a2",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#c9bfff",
        "surface-container-low": "#f1f3ff",
        "primary-container": "#0052cc",
        "on-secondary-fixed": "#1a0063",
        "inverse-primary": "#b2c5ff",
        "on-secondary": "#ffffff",
        "primary": "#003d9b",
        "surface-container": "#e9edff",
        "background": "#faf9ff",
        "tertiary": "#004b59",
        "surface-variant": "#d8e2ff",
        "surface": "#faf9ff",
        "inverse-on-surface": "#edf0ff",
        "surface-tint": "#0c56d0",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d8e2ff",
        "on-surface-variant": "#434654",
        "on-secondary-container": "#341d8d",
        "on-surface": "#051a3e",
        "outline-variant": "#c3c6d6",
        "secondary": "#5e4db9",
        "surface-container-high": "#e1e8ff",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding": "24px",
        gutter: "16px",
        unit: "4px",
      },
    },
  },
  plugins: [],
};

export default config;
