"""0001_init

Revision ID: 5c1439cddb55
Revises: 
Create Date: 2026-09-03 17:11:18.871484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c1439cddb55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('agreement_type_created_by_fkey', 'agreement_type', type_='foreignkey')
    op.create_foreign_key(None, 'agreement_type', 'user', ['created_by'], ['id'])
    op.drop_table_comment(
        'agreement_type',
        existing_comment='Master data: jenis perjanjian kontrak Altek-Klien (PKWT, PKWTT, PPJP, dll)',
        schema=None
    )
    op.alter_column('ai_screening_result', 'extracted_data',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON string (TEXT) hasil ekstraksi AI — di-review HR sebelum diterapkan ke Candidate',
               existing_nullable=True)
    op.alter_column('ai_screening_result', 'review_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending = belum direview HR, reviewed = sudah disetujui, rejected = ditolak HR',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('ai_screening_result', 'scored_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('ai_screening_result_application_id_fkey', 'ai_screening_result', type_='foreignkey')
    op.create_foreign_key(None, 'ai_screening_result', 'application', ['application_id'], ['id'])
    op.drop_table_comment(
        'ai_screening_result',
        existing_comment='Hasil AI screening: ekstraksi field CV + matching score terhadap requirement posisi',
        schema=None
    )
    op.alter_column('application', 'current_stage',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tahapan saat ini (Dijadwalkan_Interview, Interview_HR, Psikotest, Interview_User, Offering, Kontrak, Onboarding, Existing)',
               existing_nullable=True,
               existing_server_default=sa.text("'Dijadwalkan_Interview'::character varying"))
    op.alter_column('application', 'status',
               existing_type=postgresql.ENUM('active', 'rejected', 'hired', 'withdrawn', name='application_status_enum'),
               comment=None,
               existing_comment='Status keseluruhan lamaran: active / rejected / hired / withdrawn',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::application_status_enum"))
    op.alter_column('application', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('application', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_application_candidate_id', table_name='application')
    op.drop_index('idx_application_current_stage', table_name='application')
    op.drop_index('idx_application_position_id', table_name='application')
    op.drop_index('idx_application_status', table_name='application')
    op.create_index(op.f('ix_application_candidate_id'), 'application', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_position_id'), 'application', ['position_id'], unique=False)
    op.drop_constraint('application_candidate_id_fkey', 'application', type_='foreignkey')
    op.drop_constraint('application_recruiter_id_fkey', 'application', type_='foreignkey')
    op.drop_constraint('application_position_id_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'user', ['recruiter_id'], ['id'])
    op.create_foreign_key(None, 'application', 'position', ['position_id'], ['id'])
    op.create_foreign_key(None, 'application', 'candidate', ['candidate_id'], ['id'])
    op.drop_table_comment(
        'application',
        existing_comment='Lamaran — 1 kandidat bisa punya banyak application ke posisi/waktu yang berbeda',
        schema=None
    )
    op.alter_column('blacklist', 'pic_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='HR yang mengusulkan kandidat masuk blacklist',
               existing_nullable=True)
    op.alter_column('blacklist', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='HR submit → FALSE; Manager klik Approve → TRUE (default FALSE)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('blacklist', 'approved_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Manager yang menyetujui blacklist ini',
               existing_nullable=True)
    op.alter_column('blacklist', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = masih aktif dalam blacklist; FALSE = sudah dicabut (revoke)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_blacklist_candidate_id', table_name='blacklist')
    op.drop_index('idx_blacklist_is_active', table_name='blacklist')
    op.drop_index('idx_blacklist_is_approved', table_name='blacklist')
    op.drop_index('idx_blacklist_status_type_id', table_name='blacklist')
    op.create_index(op.f('ix_blacklist_candidate_id'), 'blacklist', ['candidate_id'], unique=False)
    op.drop_constraint('blacklist_approved_by_fkey', 'blacklist', type_='foreignkey')
    op.drop_constraint('blacklist_candidate_id_fkey', 'blacklist', type_='foreignkey')
    op.drop_constraint('blacklist_pic_user_id_fkey', 'blacklist', type_='foreignkey')
    op.drop_constraint('blacklist_status_type_id_fkey', 'blacklist', type_='foreignkey')
    op.create_foreign_key(None, 'blacklist', 'blacklist_status_type', ['status_type_id'], ['id'])
    op.create_foreign_key(None, 'blacklist', 'user', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'blacklist', 'user', ['pic_user_id'], ['id'])
    op.create_foreign_key(None, 'blacklist', 'candidate', ['candidate_id'], ['id'])
    op.drop_table_comment(
        'blacklist',
        existing_comment='Daftar hitam kandidat — input HR, perlu approval Manager (is_approved=TRUE) baru aktif dicek',
        schema=None
    )
    op.alter_column('blacklist_status_type', 'label',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Contoh: Menolak Offer Tanpa Alasan, No-Show, Manipulasi Data, dll',
               existing_nullable=False)
    op.alter_column('blacklist_status_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('blacklist_status_type_created_by_fkey', 'blacklist_status_type', type_='foreignkey')
    op.create_foreign_key(None, 'blacklist_status_type', 'user', ['created_by'], ['id'])
    op.drop_table_comment(
        'blacklist_status_type',
        existing_comment='Master data: jenis/kategori alasan blacklist (bisa ditambah Admin tanpa deploy)',
        schema=None
    )
    op.alter_column('candidate', 'identity_no',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='NIK KTP — untuk deteksi duplikat & blacklist match',
               existing_nullable=True)
    op.alter_column('candidate', 'source_channel',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Sumber kandidat: LinkedIn, Glints, Email, Walk-in, Referensi, dll',
               existing_nullable=True)
    op.alter_column('candidate', 'possible_duplicate',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE jika email / phone / NIK partial match dengan kandidat lain — perlu review manual',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('candidate', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('candidate', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_candidate_email', table_name='candidate')
    op.drop_index('idx_candidate_identity_no', table_name='candidate')
    op.drop_index('idx_candidate_phone', table_name='candidate')
    op.create_index(op.f('ix_candidate_email'), 'candidate', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_identity_no'), 'candidate', ['identity_no'], unique=False)
    op.create_index(op.f('ix_candidate_phone'), 'candidate', ['phone'], unique=False)
    op.drop_table_comment(
        'candidate',
        existing_comment='Data utama kandidat/talent (satu orang = 1 baris; bisa punya banyak lamaran/application)',
        schema=None
    )
    op.alter_column('candidate_document', 'doc_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='CV_asli, Foto, KTP, KK, Ijazah, Transkrip, Sertifikat, BI_Checking, dll',
               existing_nullable=False)
    op.alter_column('candidate_document', 'drive_item_id',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Microsoft Graph driveItem ID (OneDrive for Business)',
               existing_nullable=True)
    op.alter_column('candidate_document', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete — file di OneDrive tetap dihapus via Graph API, baris ini ditandai',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('candidate_document', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_candidate_document_candidate_id', table_name='candidate_document')
    op.create_index(op.f('ix_candidate_document_candidate_id'), 'candidate_document', ['candidate_id'], unique=False)
    op.drop_table_comment(
        'candidate_document',
        existing_comment='Semua dokumen kandidat disimpan per baris — fleksibel tambah tipe baru tanpa migrasi',
        schema=None
    )
    op.drop_index('idx_candidate_education_candidate_id', table_name='candidate_education')
    op.create_index(op.f('ix_candidate_education_candidate_id'), 'candidate_education', ['candidate_id'], unique=False)
    op.drop_table_comment(
        'candidate_education',
        existing_comment='Riwayat pendidikan kandidat — 1 kandidat bisa >1 entri (SMA, S1, S2, dll)',
        schema=None
    )
    op.alter_column('candidate_experience', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='NULL = masih bekerja di perusahaan tersebut (saat ini)',
               existing_nullable=True)
    op.drop_index('idx_candidate_experience_candidate_id', table_name='candidate_experience')
    op.create_index(op.f('ix_candidate_experience_candidate_id'), 'candidate_experience', ['candidate_id'], unique=False)
    op.drop_table_comment(
        'candidate_experience',
        existing_comment='Riwayat pengalaman kerja kandidat — 1 kandidat bisa >1 entri',
        schema=None
    )
    op.alter_column('client', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'client',
        existing_comment='Perusahaan klien / perusahaan tempat talent ditempatkan (mayoritas Bank)',
        schema=None
    )
    op.alter_column('employee', 'application_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Lamaran asal yang menghasilkan status karyawan ini (UNIQUE = 1 Application cuma bisa jadi 1 Employee)',
               existing_nullable=True)
    op.alter_column('employee', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Untuk hitung usia OTOMATIS — JANGAN simpan kolom usia statis',
               existing_nullable=True)
    op.alter_column('employee', 'resign_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Di-isi saat employee_status = resign',
               existing_nullable=True)
    op.alter_column('employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_employee_candidate_id', table_name='employee')
    op.drop_index('idx_employee_employee_status', table_name='employee')
    op.drop_index('idx_employee_placement', table_name='employee')
    op.create_index(op.f('ix_employee_candidate_id'), 'employee', ['candidate_id'], unique=False)
    op.drop_constraint('employee_candidate_id_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_application_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'application', ['application_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'candidate', ['candidate_id'], ['id'])
    op.drop_table_comment(
        'employee',
        existing_comment='Karyawan outsource Altek yang ditempatkan di client (terbentuk otomatis saat Application mencapai stage Existing)',
        schema=None
    )
    op.alter_column('employee_contract', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Tanggal habis kontrak — untuk alert 30/14/7 hari sebelum habis',
               existing_nullable=True)
    op.alter_column('employee_contract', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_employee_contract_employee_id', table_name='employee_contract')
    op.drop_index('idx_employee_contract_end_date', table_name='employee_contract')
    op.drop_index('idx_employee_contract_status', table_name='employee_contract')
    op.create_index(op.f('ix_employee_contract_employee_id'), 'employee_contract', ['employee_id'], unique=False)
    op.drop_constraint('employee_contract_agreement_type_id_fkey', 'employee_contract', type_='foreignkey')
    op.create_foreign_key(None, 'employee_contract', 'agreement_type', ['agreement_type_id'], ['id'])
    op.drop_table_comment(
        'employee_contract',
        existing_comment='Riwayat kontrak per employee — 1 employee bisa >1 baris (perpanjangan, resign-lalu-rehire)',
        schema=None
    )
    op.alter_column('employee_document', 'doc_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Bisa ditambah jenis baru tanpa migrasi skema — fleksibel',
               existing_nullable=False)
    op.alter_column('employee_document', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_employee_document_employee_id', table_name='employee_document')
    op.create_index(op.f('ix_employee_document_employee_id'), 'employee_document', ['employee_id'], unique=False)
    op.drop_table_comment(
        'employee_document',
        existing_comment='Dokumen karyawan: CV_terupdate, CV_template_Altek, Offering_Payslip, KK, KTP, BPJS, NPWP, dll',
        schema=None
    )
    op.alter_column('employee_payroll', 'thp',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Take Home Pay per bulan (NUMERIC = aman untuk keuangan, tidak pakai float)',
               existing_nullable=True)
    op.alter_column('employee_payroll', 'allowance_used',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Tunjangan & pinjaman (TEXT bebas format sesuai HR)',
               existing_nullable=True)
    op.alter_column('employee_payroll', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'employee_payroll',
        existing_comment='Data PAYROLL SENSITIF — dipisah tabel agar bisa kontrol akses RBAC lebih ketat (Manager & Admin only)',
        schema=None
    )
    op.alter_column('generated_cv', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Bahasa summary di CV: ID / EN',
               existing_nullable=True,
               existing_server_default=sa.text("'ID'::character varying"))
    op.alter_column('generated_cv', 'summary_source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Sumber ringkasan: AI (digenerate LLM) atau HR (ditulis manual)',
               existing_nullable=True)
    op.alter_column('generated_cv', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_generated_cv_application_id', table_name='generated_cv')
    op.drop_index('idx_generated_cv_candidate_id', table_name='generated_cv')
    op.create_index(op.f('ix_generated_cv_candidate_id'), 'generated_cv', ['candidate_id'], unique=False)
    op.drop_constraint('generated_cv_candidate_id_fkey', 'generated_cv', type_='foreignkey')
    op.drop_constraint('generated_cv_application_id_fkey', 'generated_cv', type_='foreignkey')
    op.create_foreign_key(None, 'generated_cv', 'candidate', ['candidate_id'], ['id'])
    op.create_foreign_key(None, 'generated_cv', 'application', ['application_id'], ['id'])
    op.drop_table_comment(
        'generated_cv',
        existing_comment='CV standar Altek yang sudah digenerate (Fase 2+)',
        schema=None
    )
    op.alter_column('position', 'requirement',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Requirement/kualifikasi posisi — dipakai AI untuk matching/scoring kandidat',
               existing_nullable=True)
    op.alter_column('position', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('position', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_position_client_id', table_name='position')
    op.create_index(op.f('ix_position_client_id'), 'position', ['client_id'], unique=False)
    op.drop_constraint('position_client_id_fkey', 'position', type_='foreignkey')
    op.create_foreign_key(None, 'position', 'client', ['client_id'], ['id'])
    op.drop_table_comment(
        'position',
        existing_comment='Lowongan / posisi terbuka per client (satu client bisa punya banyak position)',
        schema=None
    )
    op.alter_column('stage_history', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hasil tahapan ini: Lanjut, Not_Recommended, Lolos, Tidak_Lolos, Negosiasi_OK, Reschedule, OK, Not_OK, dll',
               existing_nullable=True)
    op.alter_column('stage_history', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User (HR/Manager) yang melakukan update pada tahapan ini',
               existing_nullable=True)
    op.alter_column('stage_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_stage_history_application_id', table_name='stage_history')
    op.drop_index('idx_stage_history_created_at', table_name='stage_history')
    op.drop_index('idx_stage_history_stage_name', table_name='stage_history')
    op.create_index(op.f('ix_stage_history_application_id'), 'stage_history', ['application_id'], unique=False)
    op.drop_constraint('stage_history_updated_by_fkey', 'stage_history', type_='foreignkey')
    op.create_foreign_key(None, 'stage_history', 'user', ['updated_by'], ['id'])
    op.drop_table_comment(
        'stage_history',
        existing_comment='Riwayat audit setiap perubahan tahapan — 1 perubahan = 1 baris, TIDAK PERNAH di-update',
        schema=None
    )
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Password di-hash dengan bcrypt (passlib), JANGAN simpan plain text',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'hr', 'manager', name='user_role_enum'),
               comment=None,
               existing_comment='Role RBAC: admin/hr/manager',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_user_email', table_name='user')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_table_comment(
        'user',
        existing_comment='Pengguna sistem (Admin, HR, Manager)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user',
        'Pengguna sistem (Admin, HR, Manager)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'hr', 'manager', name='user_role_enum'),
               comment='Role RBAC: admin/hr/manager',
               existing_nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Password di-hash dengan bcrypt (passlib), JANGAN simpan plain text',
               existing_nullable=False)
    op.create_table_comment(
        'stage_history',
        'Riwayat audit setiap perubahan tahapan — 1 perubahan = 1 baris, TIDAK PERNAH di-update',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'stage_history', type_='foreignkey')
    op.create_foreign_key('stage_history_updated_by_fkey', 'stage_history', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_stage_history_application_id'), table_name='stage_history')
    op.create_index('idx_stage_history_stage_name', 'stage_history', ['stage_name'], unique=False)
    op.create_index('idx_stage_history_created_at', 'stage_history', ['created_at'], unique=False)
    op.create_index('idx_stage_history_application_id', 'stage_history', ['application_id'], unique=False)
    op.alter_column('stage_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stage_history', 'updated_by',
               existing_type=sa.UUID(),
               comment='User (HR/Manager) yang melakukan update pada tahapan ini',
               existing_nullable=True)
    op.alter_column('stage_history', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment='Hasil tahapan ini: Lanjut, Not_Recommended, Lolos, Tidak_Lolos, Negosiasi_OK, Reschedule, OK, Not_OK, dll',
               existing_nullable=True)
    op.create_table_comment(
        'position',
        'Lowongan / posisi terbuka per client (satu client bisa punya banyak position)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'position', type_='foreignkey')
    op.create_foreign_key('position_client_id_fkey', 'position', 'client', ['client_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_position_client_id'), table_name='position')
    op.create_index('idx_position_client_id', 'position', ['client_id'], unique=False)
    op.alter_column('position', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('position', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('position', 'requirement',
               existing_type=sa.TEXT(),
               comment='Requirement/kualifikasi posisi — dipakai AI untuk matching/scoring kandidat',
               existing_nullable=True)
    op.create_table_comment(
        'generated_cv',
        'CV standar Altek yang sudah digenerate (Fase 2+)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'generated_cv', type_='foreignkey')
    op.drop_constraint(None, 'generated_cv', type_='foreignkey')
    op.create_foreign_key('generated_cv_application_id_fkey', 'generated_cv', 'application', ['application_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('generated_cv_candidate_id_fkey', 'generated_cv', 'candidate', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_generated_cv_candidate_id'), table_name='generated_cv')
    op.create_index('idx_generated_cv_candidate_id', 'generated_cv', ['candidate_id'], unique=False)
    op.create_index('idx_generated_cv_application_id', 'generated_cv', ['application_id'], unique=False)
    op.alter_column('generated_cv', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_cv', 'summary_source',
               existing_type=sa.VARCHAR(length=20),
               comment='Sumber ringkasan: AI (digenerate LLM) atau HR (ditulis manual)',
               existing_nullable=True)
    op.alter_column('generated_cv', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment='Bahasa summary di CV: ID / EN',
               existing_nullable=True,
               existing_server_default=sa.text("'ID'::character varying"))
    op.create_table_comment(
        'employee_payroll',
        'Data PAYROLL SENSITIF — dipisah tabel agar bisa kontrol akses RBAC lebih ketat (Manager & Admin only)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('employee_payroll', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee_payroll', 'allowance_used',
               existing_type=sa.TEXT(),
               comment='Tunjangan & pinjaman (TEXT bebas format sesuai HR)',
               existing_nullable=True)
    op.alter_column('employee_payroll', 'thp',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Take Home Pay per bulan (NUMERIC = aman untuk keuangan, tidak pakai float)',
               existing_nullable=True)
    op.create_table_comment(
        'employee_document',
        'Dokumen karyawan: CV_terupdate, CV_template_Altek, Offering_Payslip, KK, KTP, BPJS, NPWP, dll',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_employee_document_employee_id'), table_name='employee_document')
    op.create_index('idx_employee_document_employee_id', 'employee_document', ['employee_id'], unique=False)
    op.alter_column('employee_document', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee_document', 'doc_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Bisa ditambah jenis baru tanpa migrasi skema — fleksibel',
               existing_nullable=False)
    op.create_table_comment(
        'employee_contract',
        'Riwayat kontrak per employee — 1 employee bisa >1 baris (perpanjangan, resign-lalu-rehire)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'employee_contract', type_='foreignkey')
    op.create_foreign_key('employee_contract_agreement_type_id_fkey', 'employee_contract', 'agreement_type', ['agreement_type_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_employee_contract_employee_id'), table_name='employee_contract')
    op.create_index('idx_employee_contract_status', 'employee_contract', ['status'], unique=False)
    op.create_index('idx_employee_contract_end_date', 'employee_contract', ['end_date'], unique=False)
    op.create_index('idx_employee_contract_employee_id', 'employee_contract', ['employee_id'], unique=False)
    op.alter_column('employee_contract', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee_contract', 'end_date',
               existing_type=sa.DATE(),
               comment='Tanggal habis kontrak — untuk alert 30/14/7 hari sebelum habis',
               existing_nullable=True)
    op.create_table_comment(
        'employee',
        'Karyawan outsource Altek yang ditempatkan di client (terbentuk otomatis saat Application mencapai stage Existing)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_application_id_fkey', 'employee', 'application', ['application_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('employee_candidate_id_fkey', 'employee', 'candidate', ['candidate_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_employee_candidate_id'), table_name='employee')
    op.create_index('idx_employee_placement', 'employee', ['placement'], unique=False)
    op.create_index('idx_employee_employee_status', 'employee', ['employee_status'], unique=False)
    op.create_index('idx_employee_candidate_id', 'employee', ['candidate_id'], unique=False)
    op.alter_column('employee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('employee', 'resign_date',
               existing_type=sa.DATE(),
               comment='Di-isi saat employee_status = resign',
               existing_nullable=True)
    op.alter_column('employee', 'birth_date',
               existing_type=sa.DATE(),
               comment='Untuk hitung usia OTOMATIS — JANGAN simpan kolom usia statis',
               existing_nullable=True)
    op.alter_column('employee', 'application_id',
               existing_type=sa.UUID(),
               comment='Lamaran asal yang menghasilkan status karyawan ini (UNIQUE = 1 Application cuma bisa jadi 1 Employee)',
               existing_nullable=True)
    op.create_table_comment(
        'client',
        'Perusahaan klien / perusahaan tempat talent ditempatkan (mayoritas Bank)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('client', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'candidate_experience',
        'Riwayat pengalaman kerja kandidat — 1 kandidat bisa >1 entri',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_candidate_experience_candidate_id'), table_name='candidate_experience')
    op.create_index('idx_candidate_experience_candidate_id', 'candidate_experience', ['candidate_id'], unique=False)
    op.alter_column('candidate_experience', 'end_date',
               existing_type=sa.DATE(),
               comment='NULL = masih bekerja di perusahaan tersebut (saat ini)',
               existing_nullable=True)
    op.create_table_comment(
        'candidate_education',
        'Riwayat pendidikan kandidat — 1 kandidat bisa >1 entri (SMA, S1, S2, dll)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_candidate_education_candidate_id'), table_name='candidate_education')
    op.create_index('idx_candidate_education_candidate_id', 'candidate_education', ['candidate_id'], unique=False)
    op.create_table_comment(
        'candidate_document',
        'Semua dokumen kandidat disimpan per baris — fleksibel tambah tipe baru tanpa migrasi',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_candidate_document_candidate_id'), table_name='candidate_document')
    op.create_index('idx_candidate_document_candidate_id', 'candidate_document', ['candidate_id'], unique=False)
    op.alter_column('candidate_document', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('candidate_document', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete — file di OneDrive tetap dihapus via Graph API, baris ini ditandai',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('candidate_document', 'drive_item_id',
               existing_type=sa.VARCHAR(length=500),
               comment='Microsoft Graph driveItem ID (OneDrive for Business)',
               existing_nullable=True)
    op.alter_column('candidate_document', 'doc_type',
               existing_type=sa.VARCHAR(length=100),
               comment='CV_asli, Foto, KTP, KK, Ijazah, Transkrip, Sertifikat, BI_Checking, dll',
               existing_nullable=False)
    op.create_table_comment(
        'candidate',
        'Data utama kandidat/talent (satu orang = 1 baris; bisa punya banyak lamaran/application)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_candidate_phone'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_identity_no'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_email'), table_name='candidate')
    op.create_index('idx_candidate_phone', 'candidate', ['phone'], unique=False)
    op.create_index('idx_candidate_identity_no', 'candidate', ['identity_no'], unique=False)
    op.create_index('idx_candidate_email', 'candidate', ['email'], unique=False)
    op.alter_column('candidate', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('candidate', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('candidate', 'possible_duplicate',
               existing_type=sa.BOOLEAN(),
               comment='TRUE jika email / phone / NIK partial match dengan kandidat lain — perlu review manual',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('candidate', 'source_channel',
               existing_type=sa.VARCHAR(length=100),
               comment='Sumber kandidat: LinkedIn, Glints, Email, Walk-in, Referensi, dll',
               existing_nullable=True)
    op.alter_column('candidate', 'identity_no',
               existing_type=sa.VARCHAR(length=20),
               comment='NIK KTP — untuk deteksi duplikat & blacklist match',
               existing_nullable=True)
    op.create_table_comment(
        'blacklist_status_type',
        'Master data: jenis/kategori alasan blacklist (bisa ditambah Admin tanpa deploy)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'blacklist_status_type', type_='foreignkey')
    op.create_foreign_key('blacklist_status_type_created_by_fkey', 'blacklist_status_type', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('blacklist_status_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blacklist_status_type', 'label',
               existing_type=sa.VARCHAR(length=255),
               comment='Contoh: Menolak Offer Tanpa Alasan, No-Show, Manipulasi Data, dll',
               existing_nullable=False)
    op.create_table_comment(
        'blacklist',
        'Daftar hitam kandidat — input HR, perlu approval Manager (is_approved=TRUE) baru aktif dicek',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.create_foreign_key('blacklist_status_type_id_fkey', 'blacklist', 'blacklist_status_type', ['status_type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('blacklist_pic_user_id_fkey', 'blacklist', 'user', ['pic_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('blacklist_candidate_id_fkey', 'blacklist', 'candidate', ['candidate_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('blacklist_approved_by_fkey', 'blacklist', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_blacklist_candidate_id'), table_name='blacklist')
    op.create_index('idx_blacklist_status_type_id', 'blacklist', ['status_type_id'], unique=False)
    op.create_index('idx_blacklist_is_approved', 'blacklist', ['is_approved'], unique=False)
    op.create_index('idx_blacklist_is_active', 'blacklist', ['is_active'], unique=False)
    op.create_index('idx_blacklist_candidate_id', 'blacklist', ['candidate_id'], unique=False)
    op.alter_column('blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('blacklist', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = masih aktif dalam blacklist; FALSE = sudah dicabut (revoke)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('blacklist', 'approved_by',
               existing_type=sa.UUID(),
               comment='Manager yang menyetujui blacklist ini',
               existing_nullable=True)
    op.alter_column('blacklist', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='HR submit → FALSE; Manager klik Approve → TRUE (default FALSE)',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('blacklist', 'pic_user_id',
               existing_type=sa.UUID(),
               comment='HR yang mengusulkan kandidat masuk blacklist',
               existing_nullable=True)
    op.create_table_comment(
        'application',
        'Lamaran — 1 kandidat bisa punya banyak application ke posisi/waktu yang berbeda',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_position_id_fkey', 'application', 'position', ['position_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('application_recruiter_id_fkey', 'application', 'user', ['recruiter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('application_candidate_id_fkey', 'application', 'candidate', ['candidate_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_application_position_id'), table_name='application')
    op.drop_index(op.f('ix_application_candidate_id'), table_name='application')
    op.create_index('idx_application_status', 'application', ['status'], unique=False)
    op.create_index('idx_application_position_id', 'application', ['position_id'], unique=False)
    op.create_index('idx_application_current_stage', 'application', ['current_stage'], unique=False)
    op.create_index('idx_application_candidate_id', 'application', ['candidate_id'], unique=False)
    op.alter_column('application', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('application', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('application', 'status',
               existing_type=postgresql.ENUM('active', 'rejected', 'hired', 'withdrawn', name='application_status_enum'),
               comment='Status keseluruhan lamaran: active / rejected / hired / withdrawn',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::application_status_enum"))
    op.alter_column('application', 'current_stage',
               existing_type=sa.VARCHAR(length=100),
               comment='Tahapan saat ini (Dijadwalkan_Interview, Interview_HR, Psikotest, Interview_User, Offering, Kontrak, Onboarding, Existing)',
               existing_nullable=True,
               existing_server_default=sa.text("'Dijadwalkan_Interview'::character varying"))
    op.create_table_comment(
        'ai_screening_result',
        'Hasil AI screening: ekstraksi field CV + matching score terhadap requirement posisi',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'ai_screening_result', type_='foreignkey')
    op.create_foreign_key('ai_screening_result_application_id_fkey', 'ai_screening_result', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_screening_result', 'scored_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_screening_result', 'review_status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending = belum direview HR, reviewed = sudah disetujui, rejected = ditolak HR',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('ai_screening_result', 'extracted_data',
               existing_type=sa.TEXT(),
               comment='JSON string (TEXT) hasil ekstraksi AI — di-review HR sebelum diterapkan ke Candidate',
               existing_nullable=True)
    op.create_table_comment(
        'agreement_type',
        'Master data: jenis perjanjian kontrak Altek-Klien (PKWT, PKWTT, PPJP, dll)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'agreement_type', type_='foreignkey')
    op.create_foreign_key('agreement_type_created_by_fkey', 'agreement_type', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('agreement_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
