"""add_reset_token_to_user

Revision ID: 8c889f49d99d
Revises: dde62fd93da4
Create Date: 2026-09-05 10:21:02.129065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c889f49d99d'
down_revision: Union[str, None] = 'dde62fd93da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_reset_token'), 'user', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_token'), table_name='user')
    op.drop_column('user', 'reset_token_expires_at')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
