"""add_is_deleted_to_candidate

Revision ID: dde62fd93da4
Revises: b74baf201d04
Create Date: 2026-09-04 10:02:06.327698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde62fd93da4'
down_revision: Union[str, None] = 'b74baf201d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'is_deleted')
    # ### end Alembic commands ###
